version: "3.8"

# START build
# galleon needs DOCKER_BUILDKIT as well 
# DOCKER_BUILDKIT=1 docker compose -f docker-compose-1.yml build --no-cache
# run something inside the image
# docker run --rm -it icellmobilsoft/wildfly-mp-ms /bin/bash
# start
# docker run --rm icellmobilsoft/wildfly-mp-ms
# check labels
# docker inspect icellmobilsoft/wildfly-mp-ms:1.0.0 | jq -r '.[0].Config.Labels'
services:
  # Starting point common/Dockerfile 
  wildfly-ms-release:
    build:
      context: .
      dockerfile: dockerfile/wildfly/common/Dockerfile
      args:
        BASE_IMAGE: $BASE_IMAGE
        WILDFLY_VERSION: $WILDFLY_VERSION
        DOCKER_IMAGE_GALLEON: $DOCKER_IMAGE_GALLEON
        GALLEON_LAYERS: $GALLEON_LAYERS_MICROSERVICE
        ARTIFACT_DOWNLOADER_IMAGE: $DOCKER_IMAGE_ARTIFACT_DOWNLOADER
        POM_GROUP_ID: $LOGSTASH_POM_GROUP_ID
        POM_ARTIFACT_ID: $LOGSTASH_POM_ARTIFACT_ID
        POM_VERSION: $LOGSTASH_POM_VERSION
        POM_EXTENSION: $LOGSTASH_POM_EXTENSION
    image: $DOCKER_IMAGE_WF_MS
  wildfly-jpa-release:
    build:
      context: .
      dockerfile: dockerfile/wildfly/common/Dockerfile
      args:
        BASE_IMAGE: $BASE_IMAGE
        WILDFLY_VERSION: $WILDFLY_VERSION
        DOCKER_IMAGE_GALLEON: $DOCKER_IMAGE_GALLEON
        GALLEON_LAYERS: $GALLEON_LAYERS_JPA
        ARTIFACT_DOWNLOADER_IMAGE: $DOCKER_IMAGE_ARTIFACT_DOWNLOADER
        POM_GROUP_ID: $LOGSTASH_POM_GROUP_ID
        POM_ARTIFACT_ID: $LOGSTASH_POM_ARTIFACT_ID
        POM_VERSION: $LOGSTASH_POM_VERSION
        POM_EXTENSION: $LOGSTASH_POM_EXTENSION
    image: $DOCKER_IMAGE_WF_MS_JPA
  wildfly-full-release:
    build:
      context: .
      dockerfile: dockerfile/wildfly/common/Dockerfile
      args:
        BASE_IMAGE: $BASE_IMAGE
        WILDFLY_VERSION: $WILDFLY_VERSION
        DOCKER_IMAGE_GALLEON: $DOCKER_IMAGE_GALLEON
        GALLEON_LAYERS: full
        ARTIFACT_DOWNLOADER_IMAGE: $DOCKER_IMAGE_ARTIFACT_DOWNLOADER
        POM_GROUP_ID: $LOGSTASH_POM_GROUP_ID
        POM_ARTIFACT_ID: $LOGSTASH_POM_ARTIFACT_ID
        POM_VERSION: $LOGSTASH_POM_VERSION
        POM_EXTENSION: $LOGSTASH_POM_EXTENSION
    image: $DOCKER_IMAGE_WF_FULL
