:toc: left
:toclevels: 4
:sectnums:

= The docker-wildfly images

The repository is a collection of wildfly docker images used in icellmobilsoft,
to keep projects and their builds on the same basis.

The project can be divided into several parts, completing each other.

[IMPORTANT]
====
The docker images contain the following components:

* WildFly: 41.0.x (Jakarta EE11)
* Java: 25.x
* Base image version: 2.1.x
====

.Compatibility
[options="header"]
|===
|Version  |Jakarta EE |Java |Wildfly
//----------------------
|1.0.x (internal only)|Jakarta EE 10 |17 |WildFly 27.0.1.Final
|2.0.x (first public) |Jakarta EE 10 |17 |WildFly 27.0.1.Final
|3.0.x                |Jakarta EE 10 |17 |WildFly 30.0.1.Final
|4.0.x                |Jakarta EE 10 |21 |WildFly 34.0.1.Final
|5.0.x                |Jakarta EE 10 |21 |WildFly 38.0.1.Final
|6.0.x                |Jakarta EE 10 |21 |WildFly 39.0.1.Final
|7.0.x                |Jakarta EE 11 |25 |WildFly 41.0.1.Final
|===

The repository is a collection of wildfly docker images used in icellmobilsoft,
to keep projects and their builds on the same basis.

The project can be divided into several parts, completing each other.

== Project structure

=== /dockerfile
Collection of the dockerfiles.
For a detailed description of the docker image created, see https://i-cell-mobilsoft-open-source.github.io/docker-wildfly/[Docker Wildfly Images].

=== /script
Common scripts that are also used by dockerimages,
but can also be used on their own.

== Development
All you need to know is the following command:

[source,bash]
----
docker compose -f <PATH>/docker-compose-1.yml build
docker compose -f <PATH>/docker-compose-2.yml build
docker compose -f <PATH>/docker-compose-3.yml build
docker compose -f <PATH>/docker-compose-4.yml build
----
[IMPORTANT]
====
The release and docker push commands MUST be handled exclusively by Github Actions! 
====

== Release
The release is done by Github Actions.
Basically we handle 2 cases:

. *Major, Minor version* - major version release, can only be generated from *master branch*.
. *Bugfix version* - can only be generated from *release branch*.

The associated CI appears only for the corresponding branches.

