:toc: left
:toclevels: 4
:sectnums:

= docker-wildfly images

A repository az icellmobilsoft-ban használt Wildfly docker image-k gyűjtését szolgálja,
hogy azonos alapon működjenek a projektek és azok buildjei. 

A projekt részei több részre oszthatóak, egymást kiegészítik.

[IMPORTANT]
====
A Docker imagek a következő komponenseket tartalmazzák:

* Wildfly: 27.x (Jakarta EE10)
* Java: 17.x
* Base image version: 1.3.x FIXME:1.4.x
====

.Kompatibilitás
[options="header"]
|===
|Verzió  |Jakarta EE |Wildfly
//----------------------
|0.8.x   |Jakarta EE 8   |Widlfy 26.1.1.Final (AKARJUK?)
|1.0.x   |Jakarta EE 10  |Widlfy 27.0.1.Final
|===

The repository is a collection of wildfly docker images used in icellmobilsoft,
to keep projects and their builds on the same basis.

The project can be divided into several parts, completing each other.

== Projekt structure

=== /dockerfile
Collection of the dockerfiles.
For a detailed description of the docker image created, see FIXME[Docker Wildfly Images].

=== /script
Common scripts that are also used by dockerimages,
but can also be used on their own.

== Development
All you need to know is the following command:

[source,bash]
----
docker-compose -f <PATH>/docker-base/docker-compose-1.yml build
docker-compose -f <PATH>/docker-base/docker-compose-2.yml build
docker-compose -f <PATH>/docker-base/docker-compose-3.yml build
----
[IMPORTANT]
====
The release and docker push commands MUST be handled exclusively by Github Actions! 
====

== Release
The release is done by Github Actions.
Basically we handle 2 cases:

. *Major, Minor version* - major version release, can only be generated from *master branch*.
. *Bugfix version* - can only be generated from *release branch*.

The associated CI appears only for the corresponding branches.

