= v2.0.0

The project has moved out of the internal repository,
not counting updates, it is 1:1 compatible with version 1.1.0.

.Changes compared to the internal version

* Renames:
** wildfly-ms/default -> icellmobilsoft/wildfly-default-ms
** wildfly-jpa/default -> icellmobilsoft/wildfly-default-jpa
** wildfly-full/default -> icellmobilsoft/wildfly-default-full
** wildfly-ms/mp -> icellmobilsoft/wildfly-mp-ms
** wildfly-ms/jpa/mp -> icellmobilsoft/wildfly-mp-jpa
** wildfly-full/mp -> icellmobilsoft/wildfly-mp-full
** wildfly-ms/logstash -> icellmobilsoft/wildfly-mp-ms
** wildfly-ms/jpa-logstash -> icellmobilsoft/wildfly-mp-jpa
** wildfly-full/logstash -> icellmobilsoft/wildfly-mp-full
** wildfly-ms/oracle-jdbc -> icellmobilsoft/wildfly-mp-jpa-oracle-jdbc
** wildfly-full/oracle-jdbc -> icellmobilsoft/wildfly-mp-full-oracle-jdbc
** wildfly-ms/postgresql-jdbc -> icellmobilsoft/wildfly-mp-jpa-postgresql-jdbc
** wildfly-full/postgresql-jdbc -> icellmobilsoft/wildfly-mp-full-postgresql-jdbc
** wildfly-full/oracle-jdbc-ibm-mq -> icellmobilsoft/wildfly-mp-full-oracle-jdbc-ibm-mq
** (replaced) wildfly-ms/gcp -> icellmobilsoft/wildfly-mp-ms
** (replaced) wildfly-ms/jpa-gcp -> icellmobilsoft/wildfly-mp-jpa
** (replaced) wildfly-full/gcp -> icellmobilsoft/wildfly-mp-full
** (replaced) wildfly-ms/postgresql-jdbc-gcp -> icellmobilsoft/wildfly-mp-jpa-postgresql-jdbc
** (replaced) wildfly-full/postgresql-jdbc-gcp -> icellmobilsoft/wildfly-mp-full-postgresql-jdbc

* Environment changes:
** (new with old value) `ORACLE_DS_SERVICENAME` default `icellmobilsoft`+`DS`
** (new with old value) `POSTGRESQL_DS_CONNECTION_URL` default `icellmobilsoft`+`DS`
** (new) `CONSOLE_LOGGING_JSON_ENABLED` default `false`
** (new) `CONSOLE_LOGGING_JSON_FORMATTER_ZONEID` default `UTC`
** (change value) `FILE_LOGGING_ENABLED` default `false` (changed from `true`)
** (new with old value) `LOGSTASH_BLOCKING_MODE` default `DISCARD`
** (new with old value) `LOGSTASH_QUEUE_LENGTH` default `50000`
** (change value) `LOGSTASH_ENABLED` default `false` (changed from `true`)

* Debugging: The `--debug &ast;:8787` option doesn't need anymore in the `CMD exec` which you can ignore in the local Dockerfile mostly. The debug mode can be controlled by the `DEBUG` environment variable which is false by default. The default port is `&ast;:8787` but you can override it with the `DEBUG_PORT` environment variable.

[WARNING]
====
Don't release docker images with DEBUG enabled into production environments!

====

 
.What's new
* Baseimage version update to 1.4.0
* DEFAULT_PERSISTENCE_HIBERNATE_DIALECT variable added to the jdbc images to use in the local Dockerfiles: 
- wildfly-mp-*-oracle-jdbc image = `org.hibernate.dialect.OracleDialect`
- wildfly-mp-*-postgresql-jdbc image = `org.hibernate.dialect.PostgreSQLDialect`

[NOTE]
.project-local.Dockerfile snippet
====
You can override default dialect with `PERSISTENCE_HIBERNATE_DIALECT` environment variable but you dont need to set it in the `docker-compose.yml` file mostly.

ARG PERSISTENCE_HIBERNATE_DIALECT=$DEFAULT_PERSISTENCE_HIBERNATE_DIALECT
ENV HIBERNATE_DIALECT=$PERSISTENCE_HIBERNATE_DIALECT
====
