name: Docker compile

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v3
      - name: Run docker-compose
        run: |
          docker compose -f ./docker-compose-1.yml build --no-cache
          docker compose -f ./docker-compose-2.yml build --no-cache

          docker compose -f ./docker-compose-3.yml build wildfly-logstash-release --no-cache
          docker compose -f ./docker-compose-3.yml build wildfly-jpa-logstash-release --no-cache 
          docker compose -f ./docker-compose-3.yml build wildfly-full-logstash-release --no-cache

          docker compose -f ./docker-compose-3.yml build wildfly-oracle-jdbc-release --no-cache
          docker compose -f ./docker-compose-3.yml build wildfly-full-oracle-jdbc-release --no-cache
          docker compose -f ./docker-compose-3.yml build wildfly-postgresql-jdbc-release --no-cache
          docker compose -f ./docker-compose-3.yml build wildfly-full-postgresql-jdbc-release --no-cache

          docker compose -f ./docker-compose-3.yml build wildfly-full-oracle-jdbc-ibm-mq-release --no-cache
